max_steps = 6
seq_len = 256

[env_vars]
UCX_TLS = "all"

[model]
name = "Qwen/Qwen3-8B-Base"

[trainer.model]
impl = "custom"
compile = "None"
optim_cpu_offload = false
dp_replicate = 1
cp = 1
ep = 1

[trainer.optim]
lr = 3e-6

[orchestrator]
batch_size = 8
group_size = 4

[[orchestrator.post_batch_filters]]
type = "zero_advantage"
enforce = false

[orchestrator.renderer]
name = "qwen3"

[orchestrator.train.sampling]
max_completion_tokens = 64

[[orchestrator.train.source]]
name = "reverse-text"

[orchestrator.train.source.env.taskset]
id = "reverse-text"

[orchestrator.train.source.env.agent.harness]
id = "null"

[orchestrator.train.source.env.agent.runtime]
type = "subprocess"

[inference]

[inference.vllm]
dtype = "bfloat16"
enforce_eager = true
max_model_len = 1024
gpu_memory_utilization = 0.5
tensor_parallel_size = 2

[weight_broadcast]
type = "nixl"
protocol = "push"
host = "127.0.0.1"
port = 18001

[deployment]
type = "single_node"
num_train_gpus = 6
num_infer_gpus = 2
